// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LerKNqCnfyDehpUIzDDv2JVkCqQI3R4',
    appId: '1:653032850692:web:d807c5694852e058b4fc51',
    messagingSenderId: '653032850692',
    projectId: 'apss-62867',
    authDomain: 'apss-62867.firebaseapp.com',
    storageBucket: 'apss-62867.firebasestorage.app',
    measurementId: 'G-REY94JRFGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDscb0MIJkVm2UMq_6plGJj-Kvy5fBHCPU',
    appId: '1:653032850692:android:e66d1acd4542b59fb4fc51',
    messagingSenderId: '653032850692',
    projectId: 'apss-62867',
    storageBucket: 'apss-62867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq4SHj5KPRY2mzufwGXCXmj8hKY35Hw_8',
    appId: '1:653032850692:ios:9240bcb4c3399b5ab4fc51',
    messagingSenderId: '653032850692',
    projectId: 'apss-62867',
    storageBucket: 'apss-62867.firebasestorage.app',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq4SHj5KPRY2mzufwGXCXmj8hKY35Hw_8',
    appId: '1:653032850692:ios:9240bcb4c3399b5ab4fc51',
    messagingSenderId: '653032850692',
    projectId: 'apss-62867',
    storageBucket: 'apss-62867.firebasestorage.app',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4LerKNqCnfyDehpUIzDDv2JVkCqQI3R4',
    appId: '1:653032850692:web:6122ff40b8845a2eb4fc51',
    messagingSenderId: '653032850692',
    projectId: 'apss-62867',
    authDomain: 'apss-62867.firebaseapp.com',
    storageBucket: 'apss-62867.firebasestorage.app',
    measurementId: 'G-2TC6TK65V9',
  );

}